### ISSUE TITLE
Concurrent.futures interface

### ISSUE THREAD

**Issue by mrocklin** [lensacom/satyr#37]
Several parallel Python projects are starting converge on the `concurrent.futures` interface (both dask.distributed and IPyParallel and a couple others).  Having a consistent interface between projects is nice because users find it easy to pick up new architectures easily withouth learning a new API.  

At its most basic this interface is essentially the following:

    future = central_object.submit(...)
    results = central_object.map(...)
    result = future.result()

Which is *really* close to what is here already.  Small changes might bring this project into line with others.  

Anyway, just a thought.  Feel free to close this issue immediately if desired.

https://docs.python.org/3/library/concurrent.futures.html

**Comment by kszucs** [comment]
Agree! There is a placeholder already https://github.com/lensacom/satyr/blob/master/satyr/apis/futures.py

**Comment by kszucs** [comment]
resolved in b40fd57f20f4758612270821e29f55fa2b2a21d4
