### ISSUE TITLE
Python 3 import error

### ISSUE THREAD

**Issue by Cadarn** [lensacom/satyr#42]
When attempting to import satyr in a python 3.5 environment the following error is returned:
```python
import satyr
 File "<path>/lib/python3.5/site-packages/satyr/scheduler.py", line 58
    raise exc_type, exc_value, traceback
                  ^
SyntaxError: invalid syntax
````

**Comment by kszucs** [comment]
Satyr isn't tested against python 3 due to mesos incompatibility, see https://issues.apache.org/jira/browse/MESOS-355

**Comment by Cadarn** [comment]
Ah, ok I was unaware of this. I had assumed it was compatible as I am using python 3 and the Apache Spark framework on a Mesos cluster

**Comment by kszucs** [comment]
Spark's python support is independent from Mesos module. Spark as a mesos framework is written in Scala.

**Comment by kszucs** [comment]
I'm closing this issue now.
